### ISSUE TITLE
Newly downloaded and installed 1.0.1.0 can't sync

### ISSUE THREAD

**Issue by theDiverDK** [LIZ-project/lizus-core#4]
Just downloaded the newest windows wallet and installed it.

When i start it i get this in the logfile:

2018-02-10 10:50:55 GUI: QObject::connect: Cannot connect (null)::showProgress(QString,int) to BitcoinGUI::showProgress(QString,int)
2018-02-10 10:50:55 GUI: QObject::connect: No such signal OptionsModel::transactionFeeChanged(CAmount) in src\qt\sendcoinsdialog.cpp:178
2018-02-10 10:50:55 GUI: QObject::connect: (receiver name: 'SendCoinsDialog')

And the GUI says wallet is offline, and syncing, but nothing happens :(

I know from a friend. 1.0.0.2 works for him

**Comment by theDiverDK** [comment]
Found out i had to put:

addnode=144.217.85.81
addnode=45.76.92.72
addnode=188.226.192.178
addnode=49.169.101.242
addnode=188.226.176.158
addnode=84.17.23.44
addnode=46.56.194.126
addnode=5.77.10.13
addnode=107.174.245.117
addnode=95.175.104.23
addnode=165.227.237.199
addnode=80.56.160.22
addnode=89.178.78.231
addnode=103.75.191.120
addnode=184.82.231.66
addnode=159.89.13.212
addnode=80.208.224.85
addnode=209.205.122.194
addnode=188.166.97.220
addnode=81.200.16.254
addnode=31.168.214.160
addnode=87.255.31.232
addnode=213.87.151.132
addnode=50.100.119.157
addnode=46.4.120.126
addnode=91.195.136.112
addnode=2002:2be2:40eb::2be2:40eb
addnode=96.231.184.54
addnode=49.49.248.86
addnode=128.70.176.0
addnode=183.22.255.176
addnode=77.222.169.26
addnode=2001:0:5ef5:79fb:2c1d:3f5a:93cc:cb74
addnode=134.196.76.223
addnode=73.153.91.201
addnode=84.208.169.34
addnode=188.242.11.195
addnode=84.47.169.186
addnode=37.194.183.44
addnode=86.57.164.158
addnode=212.22.203.59
addnode=49.49.241.142
addnode=109.195.103.14
addnode=188.6.168.185
addnode=49.49.251.44
addnode=78.24.176.218
addnode=31.40.108.71
addnode=84.31.181.214
addnode=148.72.150.98
addnode=113.180.106.55
addnode=209.250.244.223
addnode=49.48.248.47
addnode=176.97.62.55
addnode=184.22.211.90
addnode=195.177.209.14
addnode=13.250.114.59
addnode=180.183.112.222
addnode=91.242.193.31
addnode=71.56.227.70
addnode=176.196.113.200
addnode=37.45.195.255
addnode=182.53.118.75
addnode=193.124.130.115
addnode=185.54.23.211
addnode=183.88.39.101
addnode=77.78.5.147
addnode=46.191.133.5
addnode=175.145.116.232
addnode=93.127.50.18
addnode=93.127.26.53
addnode=176.37.98.80
addnode=84.204.242.134
addnode=27.145.74.249
addnode=109.60.216.99
addnode=124.121.139.214
addnode=180.180.163.175

Into the config file, how come Numus wallet works with an empty config and Lizus not?

**Comment by TenchuA** [comment]
Hello, I have the same problem, but I did not saw any configfile, do you have to create it and where shall it be placed ?

**Comment by theDiverDK** [comment]
On my windows 10 machine it is located here:
%appdata%\Lizus

If there is no lizus.config file, just create it and paste alle the 'addnode' lines into it.

**Comment by TenchuA** [comment]
Thank you, now it's working.

**Comment by theDiverDK** [comment]
Glad to be able to help :)

**Comment by uaimperial** [comment]
Everything works norms

**Comment by uaimperial** [comment]
![ltz](https://user-images.githubusercontent.com/37386578/37435796-88f9c572-27ed-11e8-9b67-367cee04dbf7.jpg)

**Comment by uaimperial** [comment]
![lizus](https://user-images.githubusercontent.com/37386578/37435808-92180664-27ed-11e8-9af9-983b25446d61.jpg)

**Comment by uaimperial** [comment]
![lizus](https://user-images.githubusercontent.com/37386578/37436628-6f030788-27f1-11e8-9686-efd8cca0b2a2.jpg)
