### ISSUE TITLE
Masternode transactions missing from transaction tab

### ISSUE THREAD

**Issue by lamafist** [LIZ-project/lizus-core#9]
Masternode transactions have disappeared from the transactions tab.  The two original transactions in setting up the masternode are all that remain.

The masternode balance is correct, I can see recent masternode transactions on the dashboard tab, and the masternode is running, ENABLED, and in the masternode list.  I can also see transactions on the block explorer.

Only Transactions visible are initial transactions sent to the wallet:
![image](https://user-images.githubusercontent.com/37599684/37685482-8e0485b4-2c8b-11e8-9eb8-36cf1ffeaa99.png)

However, these are the recent transactions in dashboard:
![image](https://user-images.githubusercontent.com/37599684/37685399-4167ca0e-2c8b-11e8-9714-10ae081d53c2.png)

I am running qt wallet version 1.0.1.0 with hot-cold VPS and Windows setup.

Already tried the following without success:
1) Rescanning from the command line with "lizus-qt-1.0.1.0 -rescan"
2) Deleting everything apart from the .conf files, and wallet.dat and opening wallet again
3) Using debug console command "repairwallet"

Best regards,
LamaFist

**Comment by christiancoleman** [comment]
Hey there,

![image](https://user-images.githubusercontent.com/6051308/37715022-504645bc-2cf1-11e8-967f-e4a0f14d9643.png)

It looks like you have a filter activated. Can you click this and change it to 'All' and report back what you see?

**Comment by lamafist** [comment]
Hahahaha! PINIC!
Well spotted. I will update the call of shame...

Thanks,
Lamafist
